# Generated by Django 5.1 on 2024-12-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='cant_visitas',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='user',
            name='speciality',
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(default='1000-01-01', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
